### ISSUE TITLE
Empty attributes file leads to panic

### ISSUE THREAD

**Issue by jbfavre** [blablacar/dgr#122]
Build an ACI with an empty attribute file.
Exec `sudo dgr test`. `dgr` fails with following stack:

```
[28009.268018] init.sh[4]: Running script -> /dgr/runlevels/prestart-early/00.early.sh
[28009.278183] init.sh[4]: panic: interface conversion: interface {} is nil, not map[string]interface {}
[28009.278460] init.sh[4]: goroutine 1 [running]:
[28009.278733] init.sh[4]: github.com/blablacar/dgr/templater/merger.MergeAttributesFilesForMap(0xc8200af800, 0xc820053a80, 0x3, 0x4, 0xc8200af7d0)
[28009.278857] init.sh[4]: /home/n0rad/Work/go/src/github.com/blablacar/dgr/templater/merger/merger.go:96 +0x37e
[28009.278974] init.sh[4]: github.com/blablacar/dgr/templater/merger.MergeAttributesFiles(0xc820053a80, 0x3, 0x4, 0x4)
[28009.279077] init.sh[4]: /home/n0rad/Work/go/src/github.com/blablacar/dgr/templater/merger/merger.go:104 +0x6a
[28009.279171] init.sh[4]: github.com/blablacar/dgr/templater/merger.AttributesMerger.Merge(0xc820053a80, 0x3, 0x4, 0x0)
[28009.279361] init.sh[4]: /home/n0rad/Work/go/src/github.com/blablacar/dgr/templater/merger/merger.go:36 +0x36
[28009.279557] init.sh[4]: main.Run(0x7ffc2352df20, 0x12, 0x7ffc2352df36, 0x1, 0x7ffc2352df38, 0x4)
[28009.279769] init.sh[4]: /home/n0rad/Work/go/src/github.com/blablacar/dgr/templater/main.go:76 +0xed
[28009.279921] init.sh[4]: main.main()
[28009.279986] init.sh[4]: /home/n0rad/Work/go/src/github.com/blablacar/dgr/templater/main.go:32 +0x350
[28009.280099] init.sh[4]: goroutine 17 [syscall, locked to thread]:
[28009.280190] init.sh[4]: runtime.goexit()
[28009.280289] init.sh[4]: /usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by n0rad** [comment]
done in v68
