### ISSUE TITLE
Panic when name is not an uri

### ISSUE THREAD

**Issue by MattKetmo** [blablacar/dgr#198]
```bash
$ cat aci-manifest.yml
name: foobar

$ dgr build
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x7e3e40, 0xc420010110)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/blablacar/dgr/bin-dgr/common.ACFullname.ShortName(0xc42017d598, 0x6, 0x8, 0x84d9be)
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/bin-dgr/common/acfullname.go:101 +0xa0
main.NewAciWithManifest(0x84ac04, 0x1, 0x0, 0x0, 0x0, 0xc42017d350, 0xd, 0xc42017d340, 0xc42017cbe0, 0x42b81e, ...)
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/bin-dgr/aci.go:68 +0x6d7
main.NewAci(0x84ac04, 0x1, 0x0, 0x0, 0x0, 0xc42017d340, 0x0, 0xc42017cfe0, 0x5)
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/bin-dgr/aci.go:94 +0x225
main.NewAciOrPod(0x84ac04, 0x1, 0x0, 0x0, 0x0, 0xc42017d340, 0xc42017cf80, 0x8)
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/bin-dgr/main.go:146 +0x74
main.newBuildCommand.func1(0xc42008b860, 0x191cd70, 0x0, 0x0)
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/bin-dgr/command.go:162 +0xa5
github.com/blablacar/dgr/vendor/github.com/spf13/cobra.(*Command).execute(0xc42008b860, 0x191cd70, 0x0, 0x0, 0xc42008b860, 0x191cd70)
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/vendor/github.com/spf13/cobra/command.go:477 +0x170
github.com/blablacar/dgr/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42018ad00, 0xc420097ea0, 0xc)
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/vendor/github.com/spf13/cobra/command.go:551 +0x380
main.Execute()
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/bin-dgr/main.go:100 +0x73d
main.main()
	/home/n0rad/Work/go/src/github.com/blablacar/dgr/bin-dgr/main.go:51 +0xbb
```

**Comment by n0rad** [comment]
Fixed in v76
