### ISSUE TITLE
Panic in templater when there is a link to another dir in the dir attributes

### ISSUE THREAD

**Issue by nyodas** [blablacar/dgr#205]
```
panic: read ./attributes/..data: is a directory

goroutine 1 [running]:
panic(0x1c4580, 0xc420078ff0)
        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/blablacar/dgr/bin-templater/merger.MergeAttributesFilesForMap(0xc420078f90, 0xc42009a5e0, 0x2, 0x2, 0xc420078f90)
        /Users/bob/go/src/github.com/blablacar/dgr/bin-templater/merger/merger.go:89 +0x30a
github.com/blablacar/dgr/bin-templater/merger.MergeAttributesFiles(0xc42009a5e0, 0x2, 0x2, 0x2)
        /Users/bob/go/src/github.com/blablacar/dgr/bin-templater/merger/merger.go:113 +0x74
github.com/blablacar/dgr/bin-templater/merger.AttributesMerger.Merge(0xc42009a5e0, 0x2, 0x2, 0x0)
        /Users/bob/go/src/github.com/blablacar/dgr/bin-templater/merger/merger.go:41 +0x3f
main.Run(0x0, 0x0, 0x1f43bc, 0x1, 0x7fff5fbff580, 0x1, 0xc420072000)
        /Users/bob/go/src/github.com/blablacar/dgr/bin-templater/main.go:81 +0xbe
main.main()
        /Users/bob/go/src/github.com/blablacar/dgr/bin-templater/main.go:42 +0x1b9
```

Step to reproduce (reproduction of the config-map mount done by kubernetes)

```
cd attributes
mkdir ..109810_28_10_15_05_39.825062487  
ln -s  ..109810_28_10_15_05_39.825062487 ..data 
cd -
 ../../../dist/templater .
```

**Comment by n0rad** [comment]
fixed in v77
